services:

  postman-backend:
    image: kamal2502/postman-backend:latest
    container_name: postman-backend
    ports:
      - "5000:5000"
    environment:
      - DATABASE_URL=postgresql://postman_db_owner:npg_4ekJIAcRp3xh@ep-jolly-mouse-a4wbr9th-pooler.us-east-1.aws.neon.tech/postman_db?sslmode=require
      - JWT_SECRET=dfkljaksfhasfnlaskfjslafjskefjlsnvlfaskefjkasejflasjfklasjflajf
      - PORT=5000
      - CORS_ORIGIN=http://localhost:3000
    restart: unless-stopped
  
  postman-frontend:
    image: kamal2502/postman-frontend:latest
    container_name: postman-frontend
    ports:
      - "3000:3000"
    environment:
      - NEXT_PUBLIC_BASE_URL=http://localhost:5000/api
      - NEXT_PUBLIC_REALTIME_API_URL=localhost:5000/api
    restart: unless-stopped
