services:
#   postgres:
#     image: postgres:15
#     container_name: postbro
#     environment:
#       POSTGRES_USER: postgres
#       POSTGRES_PASSWORD: postgres
#       POSTGRES_DB: postbro
#     ports:
#       - "5432:5432"
#     volumes:
#       - postbro_data:/var/lib/postgresql/data
  
  backend:
    image: kamal2502/postman-backend:1.0.0
    container_name: postman-backend
    ports:
      - "5000:5000"
    environment:
      - DATABASE_URL=YOUR_DATABASE_URL
      - PORT=5000
      - JWT_SECRET=YOUR_JWT_SECRET
      - CORS_ORIGIN=http://localhost:3000
    restart: unless-stopped

# volumes:
#   postbro_data:
