services:
  postgres:
    image: postgres:15
    container_name: postbro
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: postbro
    ports:
      - "5432:5432"
    volumes:
      - postbro_data:/var/lib/postgresql/data

volumes:
  postbro_data:
